### ISSUE TITLE
[FEATURE] Connect dmp-api with platform-files-api

### ISSUE THREAD

**Issue by fro-profesional** [clau-org/.project-clau#18]
# Is your feature request related to a problem? Please describe

We need to decouple the file system storage from the services

# Describe the solution you'd like

Serverless service using R2 to store files

# Describe alternatives you've considered

# Additional context

# Task:

- [ ] deploy `dmp-api` for `stage` y `prod` - forge
- [ ] copy [cli_template_svc](https://github.com/clau-org/cli_template_svc) into `platform-files-api`
- [ ] connect `dmp-api` with `platform-files-api`
- [ ] create a workflow to deploy only for `dmp`
- [ ] deploy changes for all stages for both `dmp-api` and `platform-files-api`

**Comment by omar-dev-clau** [comment]
Se completo lo siguiente :
- Se desplego el servicio de Files-API en serverless
- Se probo en local y en AWS
- POC Integración del `platform-files-api` y `dmp-api`
Bugs encontrados:
- Problemas con la generacion del cliente de prisma en lambda
- Problema al actualizar el item `dmp-api` incremento del precio
