### ISSUE TITLE
[FEATURE] Create a platform invoice service 

### ISSUE THREAD

**Issue by fro-profesional** [clau-org/.project-clau#19]
# Is your feature request related to a problem? Please describe

We need to have a common platform invoice service.

# Describe the solution you'd like

Create our own invoice service using:
- https://www.facturapi.io/
- https://github.com/FacturAPI/facturapi-node

# Describe alternatives you've considered

# Additional context

# Task

- [ ] copy [cli_template_svc](https://github.com/clau-org/cli_template_svc) into `platform-invoices-api`
- [ ] Define happy path of common use cases (uses cases from `dmp`)
- [ ] connect `dmp-api`/`dmp-page` with `platform-invoices-api`
- [ ] create a workflow to deploy only for `dmp`
- [ ] deploy changes for all stages for both `dmp-api`/`dmp-page` and `platform-invoices-api`
