### ISSUE TITLE
Serverless DMP

### ISSUE THREAD

**Issue by fro-profesional** [clau-org/.project-clau#2]
Task:
- [x] Replace AWS S3 service with cloudfare R2: https://developers.cloudflare.com/r2/examples/aws-sdk-js/ - @omar-dev-clau 
- [x] Cleanup AWS - https://github.com/clau-org/.project-clau/issues/7 - @omar-dev-clau 
- [x] Migrate `rbk-api` to `dmp-api` - @fro-profesional
- [x] Deploy DMP with our repo - Netlify - @fro-profesional 
- [x] Check `dmp-api` - Just transfer the connection with Forge to this repository
- [x] Check old PRs and cleanup repo for `dmp-api` and `dmp-page`
- [x] Check `dmp-page` - https://github.com/clau-org/.project-clau/issues/14 - @omar-dev-clau 
- [x] Deploy `dmp-page` - Netlify and merchandi.xyz  - @fro-profesional 
- [x] Deploy  `dmp-page` - Cloudfare and dmp.clau-dev.com - @omar-dev-clau 
- [ ] Deploy DMP with our repo - Mobile -  https://github.com/clau-org/.project-clau/issues/15 - @fro-profesional @omar-dev-clau 
- [ ] Create a workflow for all deployments
- [ ] Deploy Files service for DMP - @omar-dev-clau 
- [ ] Connect file service with current Laravel API - @omar-dev-clau 
- [ ] Migrate files
- [x] Deploy Laravel API with a lambda - @omar-dev-clau 

Deploy:
- [x] merchandi.xyz - https://merchandi.xyz/
  - [x] clouldflare DNS - @fro-profesional 
  - [x] cloudfare Worker - @fro-profesional 
- [x] dmp-api - stage
  - [x] aws Lambda - @omar-dev-clau 
- [x] bucket.merchandi.xyz https://bucket.merchandi.xyz/hero-pic.png
  - [x] clouldflare Bucket - @fro-profesional 
- [ ] merchandi.com 
  - [ ] clouldflare DNS
  - [ ] cloudfare Worker
- [ ] dmp-api - prod
  - [ ] aws Lambda
- [ ] bucket.merchandi.com
  - [ ] clouldflare Bucket
- [ ] Android
- [ ] AppStore

Workflows:
- [ ] deploy dmp-page-web
  - env: stage
  - env: prod
- [ ] deploy dmp-page-mobile
  - env: stage
  - env: prod
- [ ] deploy dmp-api
  - env: stage
  - env: prod
- [ ] export DB
  - env: stage
  - env: prod

Analytics:
- https://umami-fro-dev-clau.koyeb.app/share/QJOqTGnu/merchandi.xyz

**Comment by fro-profesional** [comment]
@DanCuatro please review the list of task and check if you can take one

**Comment by omar-dev-clau** [comment]
https://github.com/clau-org/dmp-page-new/blob/main/wrangler.toml
https://github.com/clau-org/dmp-page-new/blob/main/serverless.yml
https://github.com/clau-org/dmp-page-new/blob/main/.gitignore
https://github.com/clau-org/dmp-page-new/blob/main/package.json
https://github.com/clau-org/dmp-page-new/blob/main/nuxt.config.ts
Enlaces de archivos a migrar
