### ISSUE TITLE
[FEATURE] Connect dmp-page with platform-files-api

### ISSUE THREAD

**Issue by fro-profesional** [clau-org/.project-clau#20]
# Is your feature request related to a problem? Please describe

We need to decouple the file system storage from the page.

# Describe the solution you'd like

Serverless service using R2 to store files

# Describe alternatives you've considered

# Additional context

# Task

- [ ] connect `dmp-page` with `platform-files-api`
- [ ] create script in `dmp-page` to migrate all images to bucket
- [ ] deploy changes for all stages for both `dmp-pages` and `platform-files-api` - if necesary
- [ ] update readme on all projects involved on how to use them - if necesary
